import type { Alert } from '../models';

export const MOCK_ALERTS: Alert[] = [
  {
    id: 'alert-001',
    severity: 'critical',
    status: 'active',
    explanation: 'Interface GigabitEthernet0/1 on router-core-01 has transitioned to DOWN state. This typically indicates a physical layer issue such as cable disconnection, port failure, or connected device power loss. The interface was previously operational and handling production traffic.',
    recommendedActions: [
      { id: 'action-001-1', actionDescription: 'Check physical cable connection at both ends', priority: 1, automatable: false },
      { id: 'action-001-2', actionDescription: 'Verify power status of connected device', priority: 2, automatable: false },
      { id: 'action-001-3', actionDescription: 'Run interface diagnostics: show interface GigabitEthernet0/1', priority: 3, automatable: true },
    ],
    sourceType: 'snmp_trap',
    device: { id: 'device-001', hostname: 'router-core-01', ipAddress: '10.0.1.1', deviceType: 'Router', vendor: 'Cisco', location: 'DC1-Rack-A01' },
    rawLog: { timestamp: new Date(Date.now() - 1000 * 60 * 5).toISOString(), message: 'linkDown NOTIFICATION-TYPE', oid: '1.3.6.1.6.3.1.1.5.3', rawData: { ifIndex: 1, ifAdminStatus: 'up', ifOperStatus: 'down' } },
    timestamp: new Date(Date.now() - 1000 * 60 * 5),
    processedAt: new Date(Date.now() - 1000 * 60 * 4),
    knowledgeEntries: [{ id: 'kb-001', content: 'IF-MIB::linkDown - Generated when interface operational status changes to down', sourceType: 'mib', relevanceScore: 0.95 }],
  },
  {
    id: 'alert-002',
    severity: 'high',
    status: 'active',
    explanation: 'CPU utilization on switch-access-05 has exceeded 85% threshold for over 10 minutes. High CPU can indicate broadcast storms, routing protocol issues, or excessive logging. Sustained high CPU may lead to packet drops and service degradation.',
    recommendedActions: [
      { id: 'action-002-1', actionDescription: 'Check for broadcast storms: show mac address-table count', priority: 1, automatable: true },
      { id: 'action-002-2', actionDescription: 'Review active processes: show processes cpu sorted', priority: 2, automatable: true },
      { id: 'action-002-3', actionDescription: 'Check for STP topology changes', priority: 3, automatable: true },
    ],
    sourceType: 'snmp_trap',
    device: { id: 'device-002', hostname: 'switch-access-05', ipAddress: '10.0.2.5', deviceType: 'Switch', vendor: 'Cisco', location: 'DC1-Rack-B03' },
    rawLog: { timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(), message: 'cpmCPURisingThreshold NOTIFICATION-TYPE', oid: '1.3.6.1.4.1.9.9.109.1.1.1', rawData: { cpmCPUTotalPhysicalIndex: 1, cpmCPUTotal5minRev: 87 } },
    timestamp: new Date(Date.now() - 1000 * 60 * 15),
    processedAt: new Date(Date.now() - 1000 * 60 * 14),
  },
  {
    id: 'alert-003',
    severity: 'medium',
    status: 'acknowledged',
    explanation: 'Authentication failure detected from IP 192.168.1.100 on firewall-edge-01. Multiple failed login attempts suggest potential unauthorized access attempt or misconfigured service account. The source IP is from the internal network.',
    recommendedActions: [
      { id: 'action-003-1', actionDescription: 'Verify source IP ownership and intended access', priority: 1, automatable: false },
      { id: 'action-003-2', actionDescription: 'Check for recent credential changes or rotations', priority: 2, automatable: false },
      { id: 'action-003-3', actionDescription: 'Review failed authentication logs for pattern', priority: 3, automatable: true },
    ],
    sourceType: 'syslog',
    device: { id: 'device-003', hostname: 'firewall-edge-01', ipAddress: '10.0.0.1', deviceType: 'Firewall', vendor: 'Palo Alto', location: 'DC1-DMZ' },
    rawLog: { timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(), message: 'Authentication failed for user admin from 192.168.1.100', facility: 'auth', rawData: { severity: 4, program: 'sshd' } },
    timestamp: new Date(Date.now() - 1000 * 60 * 45),
    processedAt: new Date(Date.now() - 1000 * 60 * 44),
  },
  {
    id: 'alert-004',
    severity: 'low',
    status: 'resolved',
    explanation: 'Configuration change detected on router-dist-02. An administrator modified the running configuration. This is an informational alert to maintain audit trail of network changes.',
    recommendedActions: [
      { id: 'action-004-1', actionDescription: 'Verify change was authorized per change management process', priority: 1, automatable: false },
      { id: 'action-004-2', actionDescription: 'Save running config to startup config if appropriate', priority: 2, automatable: true },
    ],
    sourceType: 'snmp_trap',
    device: { id: 'device-004', hostname: 'router-dist-02', ipAddress: '10.0.1.2', deviceType: 'Router', vendor: 'Juniper', location: 'DC2-Rack-A01' },
    rawLog: { timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(), message: 'ciscoConfigManEvent NOTIFICATION-TYPE', oid: '1.3.6.1.4.1.9.9.43.2.0.1' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
    processedAt: new Date(Date.now() - 1000 * 60 * 60 * 2 + 30000),
  },
  {
    id: 'alert-005',
    severity: 'info',
    status: 'active',
    explanation: 'Scheduled daily backup completed successfully on all core devices. 15 device configurations were backed up to the configuration management system without errors.',
    recommendedActions: [{ id: 'action-005-1', actionDescription: 'No action required - informational only', priority: 1, automatable: false }],
    sourceType: 'syslog',
    device: { id: 'device-005', hostname: 'nms-server-01', ipAddress: '10.0.10.1', deviceType: 'Server', vendor: 'Linux', location: 'DC1-Rack-M01' },
    rawLog: { timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(), message: 'Backup job completed: 15 devices, 0 failures', facility: 'daemon' },
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
    processedAt: new Date(Date.now() - 1000 * 60 * 60 * 6 + 1000),
  },
];
